blank_issues_enabled: false
contact_links:
  - name: ASU Research Computing
    url: https://cores.research.asu.edu/research-computing/about
    about: The main point of entry for Research Computing at ASU.
  - name: Join our Slack Channel
    url: https://asu-community.slack.com/archives/CMTPR329M
    about: Your slack channel is available for questions 24/7.
