name: New Software
description: File a software request.
labels: ["software", "request"]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this Software Request form."
  - type: input
    id: email
    attributes:
      label: Contact email
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: asurite
    attributes:
      label: ASURITE
      description: What is your ASURITE?
      placeholder: ex. acchapm1
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Software Name
      description: Name of software to be installed?
      placeholder: ex. OpenFoam
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Software version      
      placeholder: ex. 2312
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Is there anything that you want to add?   describe anything additional that you would like to be part of this request.
    validations:
      required: false
  - type: dropdown
    id: cluster
    attributes:
      label: Cluster
      description: Please choose the severity of the impact of this issue.
      multiple: false
      options:
        - 'Sol'
        - 'Phoenix'
        default: 0
    validations:
      required: true
